/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Dennis Skodda (https://sketchfab.com/SirSmitz)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/the-viking-blacksmith-dae-villages-0e01a1a363494481b2efc4ea9add8e32
Title: The Viking Blacksmith | DAE Villages
*/

"use client"

import { useRef, useEffect } from "react"
import { useGLTF, useAnimations } from "@react-three/drei"
import { a } from "@react-spring/three"
import { useFrame, useThree } from "@react-three/fiber"

import islandScene from "@/assets/3d/island.glb"

export function Island({
  isRotating,
  setIsRotating,
  setCurrentStage,
  currentFocusPoint,
  ...props
}) {
  const islandRef = useRef()
  const { gl, viewport } = useThree()
  const { nodes, materials } = useGLTF(islandScene)

  // Use a ref for the last mouse x position
  const lastX = useRef(0)
  // Use a ref for rotation speed
  const rotationSpeed = useRef(0)
  // Define a damping factor to control rotation damping
  const dampingFactor = 0.95

  // Handle pointer (mouse or touch) down event
  const handlePointerDown = (event) => {
    event.stopPropagation()
    event.preventDefault()
    setIsRotating(true)

    // Calculate the clientX based on whether it's a touch event or a mouse event
    const clientX = event.touches ? event.touches[0].clientX : event.clientX

    // Store the current clientX position for reference
    lastX.current = clientX
  }

  // Handle pointer (mouse or touch) up event
  const handlePointerUp = (event) => {
    event.stopPropagation()
    event.preventDefault()
    setIsRotating(false)
  }

  // Handle pointer (mouse or touch) move event
  const handlePointerMove = (event) => {
    event.stopPropagation()
    event.preventDefault()
    if (isRotating) {
      // If rotation is enabled, calculate the change in clientX position
      const clientX = event.touches ? event.touches[0].clientX : event.clientX

      // calculate the change in the horizontal position of the mouse cursor or touch input,
      // relative to the viewport's width
      const delta = (clientX - lastX.current) / viewport.width

      // Update the island's rotation based on the mouse/touch movement
      islandRef.current.rotation.y += delta * 0.01 * Math.PI

      // Update the reference for the last clientX position
      lastX.current = clientX

      // Update the rotation speed
      rotationSpeed.current = delta * 0.01 * Math.PI
    }
  }

  // Handle keydown events
  const handleKeyDown = (event) => {
    if (event.key === "ArrowLeft") {
      if (!isRotating) setIsRotating(true)

      islandRef.current.rotation.y += 0.005 * Math.PI
      rotationSpeed.current = 0.007
    } else if (event.key === "ArrowRight") {
      if (!isRotating) setIsRotating(true)

      islandRef.current.rotation.y -= 0.005 * Math.PI
      rotationSpeed.current = -0.007
    }
  }

  // Handle keyup events
  const handleKeyUp = (event) => {
    if (event.key === "ArrowLeft" || event.key === "ArrowRight") {
      setIsRotating(false)
    }
  }

  useEffect(() => {
    // Add event listeners for pointer and keyboard events
    const canvas = gl.domElement
    canvas.addEventListener("pointerdown", handlePointerDown)
    canvas.addEventListener("pointerup", handlePointerUp)
    canvas.addEventListener("pointermove", handlePointerMove)
    window.addEventListener("keydown", handleKeyDown)
    window.addEventListener("keyup", handleKeyUp)

    // Remove event listeners when component unmounts
    return () => {
      canvas.removeEventListener("pointerdown", handlePointerDown)
      canvas.removeEventListener("pointerup", handlePointerUp)
      canvas.removeEventListener("pointermove", handlePointerMove)
      window.removeEventListener("keydown", handleKeyDown)
      window.removeEventListener("keyup", handleKeyUp)
    }
  }, [gl, handlePointerDown, handlePointerUp, handlePointerMove])

  // This function is called on each frame update
  useFrame(() => {
    // If not rotating, apply damping to slow down the rotation (smoothly)
    if (!isRotating) {
      // Apply damping factor
      rotationSpeed.current *= dampingFactor

      // Stop rotation when speed is very small
      if (Math.abs(rotationSpeed.current) < 0.001) {
        rotationSpeed.current = 0
      }

      islandRef.current.rotation.y += rotationSpeed.current
    } else {
      // When rotating, determine the current stage based on island's orientation
      const rotation = islandRef.current.rotation.y

      /**
       * Normalize the rotation value to ensure it stays within the range [0, 2 * Math.PI].
       * The goal is to ensure that the rotation value remains within a specific range to
       * prevent potential issues with very large or negative rotation values.
       *  Here's a step-by-step explanation of what this code does:
       *  1. rotation % (2 * Math.PI) calculates the remainder of the rotation value when divided
       *     by 2 * Math.PI. This essentially wraps the rotation value around once it reaches a
       *     full circle (360 degrees) so that it stays within the range of 0 to 2 * Math.PI.
       *  2. (rotation % (2 * Math.PI)) + 2 * Math.PI adds 2 * Math.PI to the result from step 1.
       *     This is done to ensure that the value remains positive and within the range of
       *     0 to 2 * Math.PI even if it was negative after the modulo operation in step 1.
       *  3. Finally, ((rotation % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI) applies another
       *     modulo operation to the value obtained in step 2. This step guarantees that the value
       *     always stays within the range of 0 to 2 * Math.PI, which is equivalent to a full
       *     circle in radians.
       */
      const normalizedRotation =
        ((rotation % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI)

      // Set the current stage based on the island's orientation
      switch (true) {
        case normalizedRotation >= 5.45 && normalizedRotation <= 5.85:
          setCurrentStage(4)
          break
        case normalizedRotation >= 0.85 && normalizedRotation <= 1.3:
          setCurrentStage(3)
          break
        case normalizedRotation >= 2.4 && normalizedRotation <= 2.6:
          setCurrentStage(2)
          break
        case normalizedRotation >= 4.25 && normalizedRotation <= 4.75:
          setCurrentStage(1)
          break
        default:
          setCurrentStage(null)
      }
    }
  })
  return (
    <a.group ref={islandRef} {...props} dispose={null}>
      <a.group name="Sketchfab_Scene">
        <a.group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <a.group
            name="1f71105b98bb444dbe04946850819939fbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <a.group name="Object_2">
              <a.group name="RootNode">
                <a.group
                  name="Anvil_Geo"
                  position={[2.454, 16.173, 51.903]}
                  rotation={[0, 0.536, 0]}
                  scale={[0.843, 0.935, 0.843]}
                >
                  <mesh
                    name="Anvil_Geo_M_Anvil_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Anvil_Geo_M_Anvil_0.geometry}
                    material={materials.M_Anvil}
                  />
                </a.group>
                <a.group
                  name="Small_Chimney_Geo"
                  position={[-26.51, 89.512, -26.193]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={1.289}
                >
                  <mesh
                    name="Small_Chimney_Geo_M_Building_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Small_Chimney_Geo_M_Building_0.geometry}
                    material={materials.M_Building}
                  />
                </a.group>
                <a.group
                  name="Hammer_Geo"
                  position={[-12.405, 13.194, 12.169]}
                  rotation={[0, 0.242, 0]}
                  scale={1.265}
                >
                  <mesh
                    name="Hammer_Geo_M_Hammer_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Hammer_Geo_M_Hammer_0.geometry}
                    material={materials.M_Hammer}
                  />
                </a.group>
                <a.group
                  name="CoolingBath_Geo"
                  position={[36.796, 19.512, 66.636]}
                  rotation={[3.078, 1.434, -3.068]}
                  scale={1.108}
                >
                  <mesh
                    name="CoolingBath_Geo_M_Furnace_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.CoolingBath_Geo_M_Furnace_0.geometry}
                    material={materials.M_Furnace}
                  />
                </a.group>
                <a.group
                  name="Roof_Inner_Geo"
                  position={[-0.052, -2.349, -0.06]}
                >
                  <mesh
                    name="Roof_Inner_Geo_M_Building_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Roof_Inner_Geo_M_Building_0.geometry}
                    material={materials.M_Building}
                  />
                </a.group>
                <a.group
                  name="AirTube_Geo"
                  position={[8.781, 22.098, 61.512]}
                  rotation={[0, -0.327, 0]}
                  scale={0.505}
                >
                  <mesh
                    name="AirTube_Geo_M_Building_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.AirTube_Geo_M_Building_0.geometry}
                    material={materials.M_Building}
                  />
                </a.group>
                <a.group name="RoofTiles_Geo">
                  <mesh
                    name="RoofTiles_Geo_M_House_RoofTiles_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.RoofTiles_Geo_M_House_RoofTiles_0.geometry}
                    material={materials.M_House_RoofTiles}
                  />
                </a.group>
                <a.group name="Shields_Geo">
                  <mesh
                    name="Shields_Geo_M_Shields_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Shields_Geo_M_Shields_0.geometry}
                    material={materials.M_Shields}
                  />
                </a.group>
                <a.group name="Barrels_Geo">
                  <mesh
                    name="Barrels_Geo_M_Building_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Barrels_Geo_M_Building_0.geometry}
                    material={materials.M_Building}
                  />
                </a.group>
                <a.group name="Lanterns_Geo">
                  <a.group name="polySurface23">
                    <mesh
                      name="polySurface23_M_Building_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.polySurface23_M_Building_0.geometry}
                      material={materials.M_Building}
                    />
                    <a.group
                      name="polySurface22"
                      position={[-85.974, 99.303, -14.623]}
                      rotation={[0.072, 0, 0]}
                    >
                      <mesh
                        name="polySurface22_M_Building_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.polySurface22_M_Building_0.geometry}
                        material={materials.M_Building}
                      />
                      <a.group name="polySurface21" position={[0, -4.462, 0]}>
                        <mesh
                          name="polySurface21_M_Building_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.polySurface21_M_Building_0.geometry}
                          material={materials.M_Building}
                        />
                        <a.group
                          name="polySurface20"
                          position={[0, -4.724, 0]}
                          rotation={[0.081, 0, 0]}
                        >
                          <mesh
                            name="polySurface20_M_Building_0"
                            castShadow
                            receiveShadow
                            geometry={nodes.polySurface20_M_Building_0.geometry}
                            material={materials.M_Building}
                          />
                          <a.group
                            name="polySurface24"
                            position={[0, -4.835, 0]}
                          >
                            <mesh
                              name="polySurface24_M_Building_0"
                              castShadow
                              receiveShadow
                              geometry={
                                nodes.polySurface24_M_Building_0.geometry
                              }
                              material={materials.M_Building}
                            />
                            <a.group
                              name="polySurface12"
                              position={[-0.287, -8.116, -0.217]}
                            >
                              <mesh
                                name="polySurface12_M_Effects_0"
                                castShadow
                                receiveShadow
                                geometry={
                                  nodes.polySurface12_M_Effects_0.geometry
                                }
                                material={materials.M_Effects}
                              />
                            </a.group>
                            <a.group
                              name="polySurface26"
                              position={[0, -6.362, 0]}
                              scale={1.016}
                            >
                              <mesh
                                name="polySurface26_M_Effects_0"
                                castShadow
                                receiveShadow
                                geometry={
                                  nodes.polySurface26_M_Effects_0.geometry
                                }
                                material={materials.M_Effects}
                              />
                            </a.group>
                          </a.group>
                        </a.group>
                      </a.group>
                    </a.group>
                  </a.group>
                  <a.group name="Lantern_01_Geo">
                    <a.group
                      name="polySurface15"
                      position={[-0.871, 1.08, 4.67]}
                      rotation={[-0.026, 0, -0.005]}
                    >
                      <mesh
                        name="polySurface15_M_Building_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.polySurface15_M_Building_0.geometry}
                        material={materials.M_Building}
                      />
                      <a.group
                        name="polySurface14"
                        position={[121.467, 173.163, -16.096]}
                        rotation={[-0.033, 0, 0]}
                      >
                        <mesh
                          name="polySurface14_M_Building_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.polySurface14_M_Building_0.geometry}
                          material={materials.M_Building}
                        />
                        <a.group
                          name="polySurface18"
                          position={[1.575, -16.032, -1.636]}
                        >
                          <mesh
                            name="polySurface18_M_Building_0"
                            castShadow
                            receiveShadow
                            geometry={nodes.polySurface18_M_Building_0.geometry}
                            material={materials.M_Building}
                          />
                          <a.group
                            name="polySurface17"
                            position={[-0.854, 3.922, 2.356]}
                            rotation={[0.014, 0.013, 0.012]}
                          >
                            <mesh
                              name="polySurface17_M_Building_0"
                              castShadow
                              receiveShadow
                              geometry={
                                nodes.polySurface17_M_Building_0.geometry
                              }
                              material={materials.M_Building}
                            />
                            <a.group
                              name="polySurface16"
                              position={[0.169, -6.178, 0.061]}
                            >
                              <mesh
                                name="polySurface16_M_Building_0"
                                castShadow
                                receiveShadow
                                geometry={
                                  nodes.polySurface16_M_Building_0.geometry
                                }
                                material={materials.M_Building}
                              />
                              <a.group
                                name="polySurface13"
                                position={[-0.169, -6.103, -0.061]}
                                rotation={[-0.141, 0, 0]}
                              >
                                <mesh
                                  name="polySurface13_M_Building_0"
                                  castShadow
                                  receiveShadow
                                  geometry={
                                    nodes.polySurface13_M_Building_0.geometry
                                  }
                                  material={materials.M_Building}
                                />
                                <a.group
                                  name="polySurface19"
                                  position={[-0.175, -6.533, 0.064]}
                                >
                                  <mesh
                                    name="polySurface19_M_Building_0"
                                    castShadow
                                    receiveShadow
                                    geometry={
                                      nodes.polySurface19_M_Building_0.geometry
                                    }
                                    material={materials.M_Building}
                                  />
                                  <a.group
                                    name="polySurface5"
                                    position={[0.475, -9.37, 0.143]}
                                  >
                                    <mesh
                                      name="polySurface5_M_Effects_0"
                                      castShadow
                                      receiveShadow
                                      geometry={
                                        nodes.polySurface5_M_Effects_0.geometry
                                      }
                                      material={materials.M_Effects}
                                    />
                                  </a.group>
                                  <a.group
                                    name="polySurface4"
                                    position={[0.657, -10.209, 0.209]}
                                    scale={1.044}
                                  >
                                    <mesh
                                      name="polySurface4_M_Effects_0"
                                      castShadow
                                      receiveShadow
                                      geometry={
                                        nodes.polySurface4_M_Effects_0.geometry
                                      }
                                      material={materials.M_Effects}
                                    />
                                  </a.group>
                                </a.group>
                              </a.group>
                            </a.group>
                          </a.group>
                        </a.group>
                      </a.group>
                    </a.group>
                  </a.group>
                </a.group>
                <a.group name="Spear_Rack_Geo">
                  <mesh
                    name="Spear_Rack_Geo_M_WpnRack_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Spear_Rack_Geo_M_WpnRack_0.geometry}
                    material={materials.M_WpnRack}
                  />
                </a.group>
                <a.group name="Blade_Rack_Geo">
                  <mesh
                    name="Blade_Rack_Geo_M_WpnRack_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Blade_Rack_Geo_M_WpnRack_0.geometry}
                    material={materials.M_WpnRack}
                  />
                </a.group>
                <a.group name="StonePlateau_Geo">
                  <mesh
                    name="StonePlateau_Geo_M_Building_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.StonePlateau_Geo_M_Building_0.geometry}
                    material={materials.M_Building}
                  />
                </a.group>
                <a.group name="Groundplane_Geo">
                  <mesh
                    name="Groundplane_Geo_M_GroundPlane_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Groundplane_Geo_M_GroundPlane_0.geometry}
                    material={materials.M_GroundPlane}
                  />
                </a.group>
                <a.group name="Sign_Geo">
                  <a.group name="polySurface27">
                    <mesh
                      name="polySurface27_M_Building_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.polySurface27_M_Building_0.geometry}
                      material={materials.M_Building}
                    />
                  </a.group>
                  <a.group
                    name="polySurface28"
                    position={[82.309, 64.227, 6.987]}
                    rotation={[0.079, 0, 0]}
                  >
                    <mesh
                      name="polySurface28_M_Building_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.polySurface28_M_Building_0.geometry}
                      material={materials.M_Building}
                    />
                  </a.group>
                </a.group>
                <a.group name="Rocks_Geo">
                  <mesh
                    name="Rocks_Geo_M_Rocks_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Rocks_Geo_M_Rocks_0.geometry}
                    material={materials.M_Rocks}
                  />
                  <mesh
                    name="Rocks_Geo_M_Building_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Rocks_Geo_M_Building_0.geometry}
                    material={materials.M_Building}
                  />
                </a.group>
                <a.group name="Foliage_Geo">
                  <mesh
                    name="Foliage_Geo_M_Foliage_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Foliage_Geo_M_Foliage_0.geometry}
                    material={materials.M_Foliage}
                  />
                </a.group>
                <a.group name="Foliage_Opacity_Geo">
                  <mesh
                    name="Foliage_Opacity_Geo_M_Foliage_OP_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Foliage_Opacity_Geo_M_Foliage_OP_0.geometry}
                    material={materials.M_Foliage_OP}
                  />
                </a.group>
                <a.group name="Mushrooms_Geo">
                  <mesh
                    name="Mushrooms_Geo_M_Foliage_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Mushrooms_Geo_M_Foliage_0.geometry}
                    material={materials.M_Foliage}
                  />
                </a.group>
                <a.group name="Furnace_Geo">
                  <mesh
                    name="Furnace_Geo_M_Furnace_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Furnace_Geo_M_Furnace_0.geometry}
                    material={materials.M_Furnace}
                  />
                  <mesh
                    name="Furnace_Geo_M_Building_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Furnace_Geo_M_Building_0.geometry}
                    material={materials.M_Building}
                  />
                </a.group>
                <a.group name="House_Lower_Geo">
                  <mesh
                    name="House_Lower_Geo_M_House_Wood_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.House_Lower_Geo_M_House_Wood_0.geometry}
                    material={materials.M_House_Wood}
                  />
                  <mesh
                    name="House_Lower_Geo_M_Building_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.House_Lower_Geo_M_Building_0.geometry}
                    material={materials.M_Building}
                  />
                </a.group>
                <a.group name="Porch_Geo">
                  <mesh
                    name="Porch_Geo_M_Porch_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Porch_Geo_M_Porch_0.geometry}
                    material={materials.M_Porch}
                  />
                </a.group>
                <a.group
                  name="Smoke_Geo_01"
                  position={[9.282, 4.778, 121.811]}
                  rotation={[0, -0.689, 0]}
                >
                  <mesh
                    name="Smoke_Geo_01_M_Smoke_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Smoke_Geo_01_M_Smoke_0.geometry}
                    material={materials.M_Smoke}
                  />
                </a.group>
                <a.group
                  name="h"
                  position={[5.643, 5.896, 224.53]}
                  rotation={[0, -0.689, 0]}
                >
                  <mesh
                    name="h_M_Smoke_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.h_M_Smoke_0.geometry}
                    material={materials.M_Smoke}
                  />
                </a.group>
              </a.group>
            </a.group>
          </a.group>
        </a.group>
      </a.group>
    </a.group>
  )
}
